# Generated by Django 5.2.6 on 2025-09-27 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grading', '0002_alter_grade_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradeDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=50)),
                ('term', models.CharField(choices=[('TERM1', 'Term 1'), ('TERM2', 'Term 2'), ('TERM3', 'Term 3')], max_length=10)),
                ('a_count', models.IntegerField(default=0)),
                ('b_count', models.IntegerField(default=0)),
                ('c_count', models.IntegerField(default=0)),
                ('d_count', models.IntegerField(default=0)),
                ('f_count', models.IntegerField(default=0)),
                ('total_students', models.IntegerField(default=0)),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pass_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.subject')),
            ],
            options={
                'unique_together': {('subject', 'academic_year', 'term')},
            },
        ),
        migrations.CreateModel(
            name='StudentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=50)),
                ('term', models.CharField(choices=[('TERM1', 'Term 1'), ('TERM2', 'Term 2'), ('TERM3', 'Term 3')], max_length=10)),
                ('total_subjects', models.IntegerField(default=0)),
                ('average_grade', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rank_in_class', models.IntegerField(blank=True, null=True)),
                ('total_attendance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('performance_trend', models.CharField(choices=[('IMPROVING', 'Improving'), ('STABLE', 'Stable'), ('DECLINING', 'Declining')], default='STABLE', max_length=10)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.student')),
            ],
            options={
                'unique_together': {('student', 'academic_year', 'term')},
            },
        ),
    ]
