# Generated by Django 5.2.6 on 2025-09-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedreport',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='reporttemplate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reporttemplate',
            name='template_file',
        ),
        migrations.RemoveField(
            model_name='reporttemplate',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='report_type',
            field=models.CharField(choices=[('STUDENT', 'Student Report Card'), ('CLASS', 'Class Summary Report'), ('SCHOOL', 'School Summary Report')], max_length=20),
        ),
        migrations.DeleteModel(
            name='ReportSchedule',
        ),
    ]
