# Generated by Django 5.2.6 on 2025-09-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_alter_grade_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='student',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='graduation_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='grade',
            name='assessment_type',
            field=models.CharField(choices=[('EXAM', 'Exam'), ('TEST', 'Test'), ('QUIZ', 'Quiz'), ('ASSIGNMENT', 'Assignment')], max_length=20),
        ),
    ]
